# This rule is not used by the project kwarm itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the kwarm.kwarm.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kwarm
    app.kubernetes.io/managed-by: kustomize
  name: prepullimage-editor-role
rules:
- apiGroups:
  - kwarm.kwarm.io
  resources:
  - prepullimages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kwarm.kwarm.io
  resources:
  - prepullimages/status
  verbs:
  - get
