apiVersion: kwarm.kwarm.io/v1alpha1
kind: PrePullPolicy
metadata:
  labels:
    app.kubernetes.io/name: kwarm
    app.kubernetes.io/managed-by: kustomize
  name: prepullpolicy-sample
spec:
  # TODO(user): Add fields here
