apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kwarm.fullname" . }}-manager-rolebinding
  labels:
    {{- include "kwarm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kwarm.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "kwarm.serviceAccountName" . }}
  namespace: {{ include "kwarm.namespace" . }}
