apiVersion: v2
name: kwarm
description: Kubernetes Image Pre-pull Operator
type: application
version: 0.1.0
appVersion: "v0.1.0"
keywords:
  - kubernetes
  - operator
  - image
  - pre-pull
  - deployment
  - performance
home: https://github.com/bcfmtolgahan/kwarm
sources:
  - https://github.com/bcfmtolgahan/kwarm
maintainers:
  - name: bcfmtolgahan
    url: https://github.com/bcfmtolgahan
